/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as UnauthenticatedVerifyEmailRouteImport } from './routes/_unauthenticated/verify-email'
import { Route as UnauthenticatedSignUpRouteImport } from './routes/_unauthenticated/sign-up'
import { Route as UnauthenticatedSignInRouteImport } from './routes/_unauthenticated/sign-in'
import { Route as UnauthenticatedResetPasswordRouteImport } from './routes/_unauthenticated/reset-password'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as UnauthenticatedLandingRouteRouteImport } from './routes/_unauthenticated/_landing/route'
import { Route as UnauthenticatedLandingIndexRouteImport } from './routes/_unauthenticated/_landing/index'
import { Route as UnauthenticatedDemoParaglideRouteImport } from './routes/_unauthenticated/demo/paraglide'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedVerifyEmailRoute =
  UnauthenticatedVerifyEmailRouteImport.update({
    id: '/_unauthenticated/verify-email',
    path: '/verify-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const UnauthenticatedSignUpRoute = UnauthenticatedSignUpRouteImport.update({
  id: '/_unauthenticated/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedSignInRoute = UnauthenticatedSignInRouteImport.update({
  id: '/_unauthenticated/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedResetPasswordRoute =
  UnauthenticatedResetPasswordRouteImport.update({
    id: '/_unauthenticated/reset-password',
    path: '/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const UnauthenticatedLandingRouteRoute =
  UnauthenticatedLandingRouteRouteImport.update({
    id: '/_unauthenticated/_landing',
    getParentRoute: () => rootRouteImport,
  } as any)
const UnauthenticatedLandingIndexRoute =
  UnauthenticatedLandingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UnauthenticatedLandingRouteRoute,
  } as any)
const UnauthenticatedDemoParaglideRoute =
  UnauthenticatedDemoParaglideRouteImport.update({
    id: '/_unauthenticated/demo/paraglide',
    path: '/demo/paraglide',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof UnauthenticatedLandingIndexRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/reset-password': typeof UnauthenticatedResetPasswordRoute
  '/sign-in': typeof UnauthenticatedSignInRoute
  '/sign-up': typeof UnauthenticatedSignUpRoute
  '/verify-email': typeof UnauthenticatedVerifyEmailRoute
  '/demo/paraglide': typeof UnauthenticatedDemoParaglideRoute
}
export interface FileRoutesByTo {
  '/': typeof UnauthenticatedLandingIndexRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/reset-password': typeof UnauthenticatedResetPasswordRoute
  '/sign-in': typeof UnauthenticatedSignInRoute
  '/sign-up': typeof UnauthenticatedSignUpRoute
  '/verify-email': typeof UnauthenticatedVerifyEmailRoute
  '/demo/paraglide': typeof UnauthenticatedDemoParaglideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_unauthenticated/_landing': typeof UnauthenticatedLandingRouteRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_unauthenticated/reset-password': typeof UnauthenticatedResetPasswordRoute
  '/_unauthenticated/sign-in': typeof UnauthenticatedSignInRoute
  '/_unauthenticated/sign-up': typeof UnauthenticatedSignUpRoute
  '/_unauthenticated/verify-email': typeof UnauthenticatedVerifyEmailRoute
  '/_unauthenticated/demo/paraglide': typeof UnauthenticatedDemoParaglideRoute
  '/_unauthenticated/_landing/': typeof UnauthenticatedLandingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/tasks'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/demo/paraglide'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/tasks'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/demo/paraglide'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_unauthenticated/_landing'
    | '/_authenticated/profile'
    | '/_authenticated/tasks'
    | '/_unauthenticated/reset-password'
    | '/_unauthenticated/sign-in'
    | '/_unauthenticated/sign-up'
    | '/_unauthenticated/verify-email'
    | '/_unauthenticated/demo/paraglide'
    | '/_unauthenticated/_landing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  UnauthenticatedLandingRouteRoute: typeof UnauthenticatedLandingRouteRouteWithChildren
  UnauthenticatedResetPasswordRoute: typeof UnauthenticatedResetPasswordRoute
  UnauthenticatedSignInRoute: typeof UnauthenticatedSignInRoute
  UnauthenticatedSignUpRoute: typeof UnauthenticatedSignUpRoute
  UnauthenticatedVerifyEmailRoute: typeof UnauthenticatedVerifyEmailRoute
  UnauthenticatedDemoParaglideRoute: typeof UnauthenticatedDemoParaglideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/verify-email': {
      id: '/_unauthenticated/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof UnauthenticatedVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/sign-up': {
      id: '/_unauthenticated/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof UnauthenticatedSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/sign-in': {
      id: '/_unauthenticated/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof UnauthenticatedSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/reset-password': {
      id: '/_unauthenticated/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof UnauthenticatedResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_unauthenticated/_landing': {
      id: '/_unauthenticated/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedLandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/_landing/': {
      id: '/_unauthenticated/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedLandingIndexRouteImport
      parentRoute: typeof UnauthenticatedLandingRouteRoute
    }
    '/_unauthenticated/demo/paraglide': {
      id: '/_unauthenticated/demo/paraglide'
      path: '/demo/paraglide'
      fullPath: '/demo/paraglide'
      preLoaderRoute: typeof UnauthenticatedDemoParaglideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface UnauthenticatedLandingRouteRouteChildren {
  UnauthenticatedLandingIndexRoute: typeof UnauthenticatedLandingIndexRoute
}

const UnauthenticatedLandingRouteRouteChildren: UnauthenticatedLandingRouteRouteChildren =
  {
    UnauthenticatedLandingIndexRoute: UnauthenticatedLandingIndexRoute,
  }

const UnauthenticatedLandingRouteRouteWithChildren =
  UnauthenticatedLandingRouteRoute._addFileChildren(
    UnauthenticatedLandingRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  UnauthenticatedLandingRouteRoute:
    UnauthenticatedLandingRouteRouteWithChildren,
  UnauthenticatedResetPasswordRoute: UnauthenticatedResetPasswordRoute,
  UnauthenticatedSignInRoute: UnauthenticatedSignInRoute,
  UnauthenticatedSignUpRoute: UnauthenticatedSignUpRoute,
  UnauthenticatedVerifyEmailRoute: UnauthenticatedVerifyEmailRoute,
  UnauthenticatedDemoParaglideRoute: UnauthenticatedDemoParaglideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
